services:
  backend:
    image: mysite-backend
    container_name: mysite-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: mysite-frontend
    pull_policy: never
    container_name: mysite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    container_name: mysite-mongodb
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase

  mongo-express:
    image: mongo-express:latest
    container_name: mysite-mongo-express
    ports:
      - 8081:8081
    env_file: 
      - ./mongo-express/.env

  

volumes:
  mongo_data:
