name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        working-directory: ./backend
        run: |
          pytest -v

  docker-build:
    needs: backend-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
                    username: ${{ secrets.username}}
                    password: ${{ secrets.password }}
          # Ensure that DOCKER_USERNAME and DOCKER_PASSWORD are set in your repository's GitHub Actions secrets.

      - name: Build and push backend image
        run: |
          docker build -t  ${{ secrets.username}}/mysite-backend:latest ./backend
          docker push ${{ secrets.password }}/mysite-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t  ${{ secrets.username}}/mysite-frontend:latest ./frontend
          docker push ${{ secrets.password }}/mysite-frontend:latest
